export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const METRICS_DATA_RECEIVED = "METRICS DATA RECEIVED";
export const UPDATE_SELECTED_METRICS = "UPDATE SELECTED METRICS";
